### ISSUE TITLE
WarmUp of Service Applications necessary?

### ISSUE THREAD

**Issue by chrisstherock** [spjeff/spbestwarmup#1]
Hello everyone,

By running the script it will generate some 404, 400 und 500 HTTP Errors with Service Applications. In many cases the SA are woking fine and futher investigations are mostly not needfull. Therefore my questions:
1. Why is it necessary to warm up those SA? Over severall months I don't really noticed a performance improvement by accessing the SA (over CA or HTTP Call) after the script has run. Or where can I notice the improvement? Maybe a switch to skip the Service Application WarmUp would be helpful, too.
2. To prevent the event log from flooding, could it be possible to prevent the script from writing to the log? Just like Andrew mentioned it at the [old issue at CodePlex].(https://spbestwarmup.codeplex.com/discussions/647957)

My test instance: Single Server SP 2013 installed with AutoSP Installer

Now I am interested in your thoughts and experiences.

Best regards 
Christian

P.S.: Thank you very much for this outrageous product maintenance over the last time. I really enjoy watching this project evolving. Keep up the good work!

**Comment by spjeff** [comment]
Great suggestion.  Updated PowerShell PS1 with "-skiplog" to suppress Event Log.  Updated the download release.

https://github.com/spjeff/spbestwarmup/commit/3bdc8138f1037a478a77fa7d7da05550e8daf483

Each service application behaves differently and while it may give HTTP 500 for warm up other well formatted traffic can benefit from having IIS load the needed DLL be and more ready for requests.   For simplicity, all Service Applications here are loaded the same way.

**Comment by chrisstherock** [comment]
Thank you very much for this quick implementation but I think there is something wrong:

![image](https://cloud.githubusercontent.com/assets/18526774/14667667/9f687158-06e0-11e6-99e3-b825b20d9336.png)

**Comment by spjeff** [comment]
Typo, missing $ prefix on variable.   Please try now.

**Comment by chrisstherock** [comment]
It's working now. now the script won't throw log entry. The SP Server prompt some events because of the failed requests. But that can only be fixed by excluding those SA from the warmup or fixing the problems if it's possible.

Example entry:
![image](https://cloud.githubusercontent.com/assets/18526774/14673933/2d1fd250-0701-11e6-8cf8-9c4f04936c53.png)

**Comment by Kofl** [comment]
Hi,

I am in the same boat then chrisstherock. I also get red eventlog entries for not being able to warm up specific SAs. Not nice for monitoring the eventlog for errors. 

Would it be possible to define exclusions?

Best,
Thomas

**Comment by spjeff** [comment]
Please test the latest version 2.4.5.

Added parameter "-ssa" or "-skipserviceapps" to avoid warm up of Service Application Endpoint URLs.

https://github.com/spjeff/spbestwarmup/commit/2bd811329c19c8c332c8983fe1df8f13a493708d#diff-316afa53af12494556ef094f27de1d72
