### ISSUE TITLE
Password Auto detect fails; script stops

### ISSUE THREAD

**Issue by crossan007** [spjeff/spbestwarmup#12]
Password auto detect attempt fails on server 2008R2 / SharePoint 2010.

![image](https://cloud.githubusercontent.com/assets/11679900/25288206/686c9aa8-2692-11e7-8359-891b8ab55b56.png)

**Comment by crossan007** [comment]
This script requires PowerShell 3.0 + for Get-CIMInstance to work.

**Comment by spjeff** [comment]
Hi Charles,

Which version of PowerShell is running?  ($host.version)   I don't have Server 2008R2 to test with.

**Comment by crossan007** [comment]
PS2.0 is "out of box" on Server 2008R2.  It's trivial to upgrade WMF (and PowerShell) to 5.1.

**Comment by crossan007** [comment]
I should have seen this before upgrading PowerShell...

https://support.microsoft.com/en-us/help/2796733/sharepoint-2010-management-shell-does-not-load-with-windows-powershell-3.0.

It seems that PS3.0 cannot be used to manage SP2010, but I think this script depends on SP3.0+.

**Comment by spjeff** [comment]
How about another way to read IIS WAMUserName/WAMUserPass?  Does this run OK on Server 2008R2?

$tmp = Get-WMIObject -class IISApplicationPoolSetting -namespace "root\microsoftiisv2" -computer $env:computername
$tmp | select WAM* |ft -a

**Comment by crossan007** [comment]
This call works

**Comment by crossan007** [comment]
Looks like  ```get-CimInstance``` is used twice in the script - the other place is for setting up scheduled tasks.

**Comment by spjeff** [comment]
Yes, sure does.  How does this look?  Updated and saved a commit.

https://github.com/spjeff/spbestwarmup/commit/123aae91c6c8c488c1ce5c55006880c5190c7cbc

**Comment by spjeff** [comment]
Believe this is now resolved.  Closing.
