### ISSUE TITLE
Office Web Apps / Office Online Server WarmUp ?

### ISSUE THREAD

**Issue by cangot** [spjeff/spbestwarmup#15]
Hi, 

When building SP2013/SP2016 Farm, usually also a Office Web Apps / Office Online Server Farm for Office are added (For document preview capability inside the browser). 

I have noticed a performance difference when accessing a document preview for the first time and the second time (For each file type). 

It could be interesting to have this warmed up too ? 

Let me know your thoughts. 

PS : Thanks for your useful tool.

**Comment by spjeff** [comment]
Good suggestion!   Which version of Office Web Apps do you run?   
SP2010/SP2013 have Office Web Apps while SP2016 has Office Online Server.

Know a good cmdlet to discover the URL endpoints?   `gcm *wopi*` may help.  If we can find the URLs I'm glad to add that feature.

**Comment by cangot** [comment]
I'm a SharePoint consultant, my customers have mostly Office Web Apps (SP2013) and Office Online Server (SP2016).
I think the 2 are basically the same thing under the hood, so if we find a warm up method, it will mostlikely work in both cases. I'll try to have a look at it as soon as I can.

Thanks again.

**Comment by spjeff** [comment]
Version 2.4.4 added support for Get-SPWOPIBinding (OOS/WAC).

Please see most recent commit and give it a test.
  
https://github.com/spjeff/spbestwarmup/commit/e34feee930ff3b5f95aafcffe2f4b423dfc5c876#diff-316afa53af12494556ef094f27de1d72

**Comment by cangot** [comment]
Thanks ! I'll give it a try as soon as I can...
