### ISSUE TITLE
Search Warm Up ?

### ISSUE THREAD

**Issue by cangot** [spjeff/spbestwarmup#16]
Using REST API  ?

https://msdn.microsoft.com/fr-fr/library/office/jj163876.aspx

Note : Can be done with custom URLs in the meantime

**Comment by spjeff** [comment]
Good idea!  Added URL to web application warm up.

https://github.com/spjeff/spbestwarmup/commit/d06b3bd4ad21a641f004eada12208a96d0b724aa#diff-316afa53af12494556ef094f27de1d72

**Comment by cangot** [comment]
Thanks : I'll suggest to use an other keyword such as "warmup" or "spbestwarmup".
My point is to avoid "polluting" Search Top queries Reports : So we know that this entry with "warmup" is not related with actual user searches : https://technet.microsoft.com/en-us/library/jj219554.aspx

**Comment by spjeff** [comment]
Excellent point.  Updated with keyword "warmup"

https://github.com/spjeff/spbestwarmup/commit/52c3e6d5fa0c375e588e3d897d9794fa5cc3c396#diff-316afa53af12494556ef094f27de1d72
