### ISSUE TITLE
Limited msg...

### ISSUE THREAD

**Issue by tchab2** [spjeff/spbestwarmup#17]
Hi folks,

Unfortunatly, the script is working but the _$global:msg_ is limited to 32766 then the script is not able to complete to Event Log.

![image](https://user-images.githubusercontent.com/3036151/27046760-ada97dac-4f73-11e7-9201-b8830dc69730.png)

**Comment by spjeff** [comment]
Updated error handling.  Please test the latest version 2.4.4

https://github.com/spjeff/spbestwarmup/commit/ef53bf424cd3249a2b108f35cb0b6aeaa035a8bb#diff-316afa53af12494556ef094f27de1d72
