### ISSUE TITLE
Typo error in readme for installing the script

### ISSUE THREAD

**Issue by jeffangama** [spjeff/spbestwarmup#19]
It shall be 

SPBestWarmUp.ps1 -i

instead of

SPBestWarmup.ps1 -i
(Triggers error in powershell)

Thanks for your great script, been using it multiple times now

**Comment by spjeff** [comment]
Thanks.  Where did you see this?  Line number?

In the PS1 file I only see CamelCase ("Up.ps1") everywhere.,

**Comment by jeffangama** [comment]
On the readme page of the github page

https://github.com/spjeff/spbestwarmup

**Currently as** 
Run SPBestWarmup.ps1 -f to install farm wide. Creates Task Scheduler job on every machine.
Run SPBestWarmup.ps1 -i to install locally. Creates Task Scheduler job on the local machine.
Run SPBestWarmup.ps1 -u to uninstall farm wide. Deletes any Task Scheduler job named "SPBestWarmup"

**Comment by spjeff** [comment]
Update to Camel Case in Readme
