### ISSUE TITLE
Question - Clearing the INetCache

### ISSUE THREAD

**Issue by JoeAlanis** [spjeff/spbestwarmup#22]
Hi Jeff,

I'm a fan of your work. The legacy version of your script on hosted on script center has a couple lines to clear the the INetCache. [https://gallery.technet.microsoft.com/office/SPBestWarmUp-Warmup-e7c77527](url)

I noticed that this is not included in the version hosted here on github. There was a blog article [http://www.adventuresinsharepoint.co.uk/2016/02/22/disk-space-filling-up-on-web-front-end-servers/](url) where they mentioned the INetCache/IE folder filling up disk space with a proposed fix. Do you have any thoughts on this or why clearing the INetCache is not included in the current version of your script?

Thanks,
Joe

**Comment by spjeff** [comment]
Good question Joe.

That was removed because we're no longer using IE COM Object for running page loads.  Only pure HTTP from PowerShell, so shouldn't be an issue anymore.

**Comment by JoeAlanis** [comment]
Thank you Jeff!
