### ISSUE TITLE
Existince of Load Balancer

### ISSUE THREAD

**Issue by martinlingstuyl** [spjeff/spbestwarmup#25]
Hi Jeff,

Does this script take into account the existence of a load balancer? If not, we would not want to only warm up a single front end machine in a farm if the next request might just be redirected to a different machine that has not be warmed up.

what are your ideas on this?

Kind regards,
Martin

**Comment by spjeff** [comment]
Covered with "-farminstall" for machines.

Works for load balancer and covers service applications, etc.

**Comment by martinlingstuyl** [comment]
Hi Jeff,

I can see it calls the Service Applications by servername.  But if it calls for example: https://contoso.org.local that call would be load balanced (as it resolves to the loadbalancer), even if it was called from all the servers, or am I wrong in this?

**Comment by spjeff** [comment]
Yes, -farminstall covers that also

**Comment by martinlingstuyl** [comment]
ok, thanks!
