### ISSUE TITLE
URLs' line numbers

### ISSUE THREAD

**Issue by hasankoroglu** [spjeff/spbestwarmup#29]
Hi @spjeff,

First thanks for this great script.

This issue not very important but it would nice to correct line numbers.

In SPBestWarmUp.ps1 at line 6,

> Please modify lines 374-395 to suit your portal content design

But the URLs at line between 350 - 368 .

Probably after update the script changes the line numbers.

Thanks again 👍

**Comment by spjeff** [comment]
Thanks.  Updated.
