### ISSUE TITLE
spbestwarmup not compatible to SharePoint 2010 

### ISSUE THREAD

**Issue by ok-stp** [spjeff/spbestwarmup#3]
It seems that the script is not compatible to SharePoint 2010 with the following scenario:
- Windows Server 2008 R2
- Windows Management Framework 3
- SharePoint Server 2010 with latest Patches

The SharePoint cmdlets are not compatible to PowerShell 3 but the Script needs PowerShell 3 to run. 
I'm getting the following Exception:

```
System.PlatformNotSupportedException: Microsoft SharePoint wird mit der Version 4.0.30319.34209 der Laufzeitversion von Microsoft .NET nicht unterstützt.
   bei Microsoft.SharePoint.Administration.SPConfigurationDatabase.get_Farm()
   bei Microsoft.SharePoint.Administration.SPFarm.FindLocal(SPFarm& farm, Boolean& isJoined)
   bei Microsoft.SharePoint.PowerShell.SPCmdlet.BeginProcessing()
```

**Comment by spjeff** [comment]
What happens if you delete the first line?
#requires -version 3.0

That was meant to ensure a minimum functional level.  With PowerShell 5 now out I haven't tested all the way back to PowerShell 2.   Might work OK.  Please let me know if removing that lines helps resolve.

**Comment by ok-stp** [comment]
i've deleted the first line (#requires -version 3.0), now the script is running without any error.
thank you very much!

**Comment by spjeff** [comment]
Cool, thanks for testing!   I removed the first line to ensure wider compatibility.   

https://github.com/spjeff/spbestwarmup/commit/2d3925ed3ba197ee50d22c47e7aee8881a3ce20e
