### ISSUE TITLE
Long running script

### ISSUE THREAD

**Issue by Struijky** [spjeff/spbestwarmup#31]
When running SPBestWarmUp.ps1 from the PowerShell console it takes several minutes before any output is displayed.
I figured out this caused by the CreateLog() function:
The check for the presence of the SPBestWarmUp Event Log Source:
!(Get-EventLog -LogName Application -Source "SPBestWarmUp" -ErrorAction SilentlyContinue)
Collects all SPBestWarmUp Events which consumes a lot of time.
I know Event Logs need to be cleaned on a regular basis but besides I prefer to run the check with the '-Newest 1' parameter like:
!(Get-EventLog -LogName Application -Source "SPBestWarmUp" -Newest 1 -ErrorAction SilentlyContinue)

**Comment by spjeff** [comment]
Excellent idea Struijky.   Updated PS1 code with "-Newest 1"

**Comment by spjeff** [comment]
https://github.com/spjeff/spbestwarmup/commit/27d04f04e9c1a96eb128edce1161f70dc52efd3a#diff-13f1021d544874b5cf340e171b1a24f5e973a9cd9fa5d5b4cecd482a2966fc25

**Comment by Struijky** [comment]
Hi Jeff,

My pleasure to help, great script btw., I advise most of my customers to implement it.
I ran into this issue by accident and thought I should report it.

Best regards,

Hans Struijk

Senior SharePoint
Consultant, Architect
Spoormakerserf 91
5706 KX Helmond
+31 (0) 6 13326926
info@sigylon.nl<mailto:info@sigylon.nl>
[cid:image002.png@01D6D90B.44F4A640]
