### ISSUE TITLE
The $global:msg variable isn't initialized

### ISSUE THREAD

**Issue by Struijky** [spjeff/spbestwarmup#32]
The $global:msg variable isn't initialized. This will give an error while writing the message to the Event Log when SPBEstWarmUp.ps1 is ran multiple times in the PowerShell console window.
I suggest to initialize the variable to an empty string in the main section of the script to prevent this.

**Comment by spjeff** [comment]
Thank you Struijky.  Great suggestion Updated PS1 with code change.

**Comment by spjeff** [comment]
Updated at https://github.com/spjeff/spbestwarmup/commit/27d04f04e9c1a96eb128edce1161f70dc52efd3a#diff-13f1021d544874b5cf340e171b1a24f5e973a9cd9fa5d5b4cecd482a2966fc25

**Comment by Struijky** [comment]
Hi Jeff,

Good to hear I could help.

Best regrads,

Hans Struijk

Senior SharePoint
Consultant, Architect
Spoormakerserf 91
5706 KX Helmond
+31 (0) 6 13326926
info@sigylon.nl<mailto:info@sigylon.nl>
[cid:image002.png@01D6D90B.72521D20]
