### ISSUE TITLE
Console output bug

### ISSUE THREAD

**Issue by drullo** [spjeff/spbestwarmup#35]
In `NavigateTo`, line 502 calls `WriteLog` with a `-NoNewline` switch, but `WriteLog` doesn't support this switch.  So the output (error codes) are displayed on the next line instead of next to the URL that they are associated with.  In my environment, I resolved this by changing this line to a `Write-Host` instead of `WriteLog` since it's not changing colors.

**Comment by spjeff** [comment]
Excellent ideas Dan.  Thank you.   Updated with https://github.com/spjeff/spbestwarmup/commit/c40298d3f3436d6d061c66c9267944aa266242f8
