### ISSUE TITLE
String concatenation bug in WOPI services loop

### ISSUE THREAD

**Issue by drullo** [spjeff/spbestwarmup#36]
In `WarmUp`, the concatenation logic on lines 494 and 495 is incorrect - resulting in incomplete URLs that only include the protocol prefix and the hostname.

One possible solution is to wrap the content in parenthesis.  This is what I chose to do in my environment:
`NavigateTo ("https://$w"+":810/$s/")`

Another possible solution is to make it a single string (no plus sign) and prefix the colon with an escape character:
NavigateTo "https://$w`:810/$s/"

**Comment by spjeff** [comment]
Excellent ideas Dan.  Thank you.   Updated with https://github.com/spjeff/spbestwarmup/commit/c40298d3f3436d6d061c66c9267944aa266242f8
