### ISSUE TITLE
OOS Services

### ISSUE THREAD

**Issue by mdroschak-CP** [spjeff/spbestwarmup#38]
In the foreach loop for the OOS services on lines 475 and 476 there are trailing forward slashes at the end of the string that is causing an error in my environment.  I removed the slashes to prevent the errors in my SharePoint 2019 environment.  

```        
foreach ($s in $services) {
            NavigateTo ("http://$w"+":809/$s")
            NavigateTo ("https://$w"+":810/$s")
        }
```

**Comment by spjeff** [comment]
Thank you.  Updated and resolved.

https://github.com/spjeff/spbestwarmup/commit/48fe31247a60643359f7a4f14d00a9a429ef9c75
