### ISSUE TITLE
SP Security Token Service 

### ISSUE THREAD

**Issue by mdroschak-CP** [spjeff/spbestwarmup#39]
In my SharePoint 2019 environment, the endpoint for `spsecuritytokenservice.svc` on line 360 requires `site/` to be prefixed in order to work.  Don't know if that is specific to just SharePoint 2019.

```diff
- NavigateTo $url"_vti_bin/sts/spsecuritytokenservice.svc"
+ NavigateTo $url"site/_vti_bin/sts/spsecuritytokenservice.svc"
```

I would imagine this same change would apply to line 460, but I don't have Project Server configured to test it out.  

[SharePoint Security Token Service Reference](https://learn.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-spstws/4fd7b12f-ece6-4e7e-b72c-24be8af10458)

**Comment by spjeff** [comment]
Seems environment specific.  Root URL worked OK here.
