### ISSUE TITLE
Error when running the -f flag

### ISSUE THREAD

**Issue by anbarak** [spjeff/spbestwarmup#4]
SCHTASKS CREATE on myfrontendserver.contoso.com

> Method invocation failed because [System.IO.IOException] does not contain a
> method named 'op_Addition'.
> At C:\Scripts\SPBestWarmUp.ps1:314 char:4
> -             $global:msg += $error[0].Exception + "`r`n" +
>   $error[0].ErrorDetails.Message
>   +
> 
> ```
>     + CategoryInfo          : InvalidOperation: (op_Addition:String) [], Runti
>    meException
>     + FullyQualifiedErrorId : MethodNotFound
> ```

**Comment by spjeff** [comment]
Thanks Haarabi.  I updated to cast Exception message to String() format before display.

Would you please download the latest and give it a test run?

**Comment by spjeff** [comment]
Fixed with commit 
https://github.com/spjeff/spbestwarmup/commit/e3b4042bb5989f1883379591aa3ddc228c77efba#diff-316afa53af12494556ef094f27de1d72
