### ISSUE TITLE
Internet Explorer window opens.

### ISSUE THREAD

**Issue by MLCarter1976** [spjeff/spbestwarmup#5]
I am on sp 2013 sp1 ent ed and i have errors "the page you're looking for doesn't exist"  this happened on different  versions.   Feb 2016 cu and may 2016 cu.    Both running powershell as farm amin on vm hyper-v rdp and version 2.0.11 worked without the window pop up using the same method.  
I even went to .\spbestwarmup.ps1 -install and got error with admin sp2013 management shell as farm admin account

**Comment by MLCarter1976** [comment]
2.2.4 shows this with parameter USL seem to be the same as url

> > .PARAMETER url
> >   Typing "SPBestWarmUp.ps1 -install" will create a local Task Scheduler job under credentials of the
> >   current user.  Job runs every 60 minutes on the hour to help automatically populate cache.  
> >   Keeps cache full even after IIS daily recycle, WSP deployment, reboot, or other system events.
> 
> .PARAMETER install
>   Typing "SPBestWarmUp.ps1 -install" will create a local Task Scheduler job under credentials of the
>   current user.  Job runs every 60 minutes on the hour to help automatically populate cache.  
>   Keeps cache full even after IIS daily recycle, WSP deployment, reboot, or other system events.

Version 2.0.11 shows url and install with different text.  I assume it was as mistake of cut and paste :)
THANK YOU for the details, they help me out greatly!  Love it!

> .PARAMETER Url
>     A collection of url that will be added to the list of websites the script will fetch.
> .PARAMETER Install
>     Typing "SPBestWarmUp.ps1 -install" will create a local Task Scheduler job under credentials of the
>     current user.  Job runs every 60 minutes on the hour to help automatically populate cache after
>     nightly IIS recycle.

**Comment by spjeff** [comment]
Updated header with URL parameter description.

https://github.com/spjeff/spbestwarmup/commit/f2ccb27a1fa543e8ccab8d2ba81c40cebba494bb#diff-316afa53af12494556ef094f27de1d72
