### ISSUE TITLE
server 2008 R2 Script Issue

### ISSUE THREAD

**Issue by pwilliams134** [spjeff/spbestwarmup#6]
I am having issue runing the script with server 2008 R2. It keep saying "Get-CimIntance" is not recognize as the name of a cmdlet. Can you help?

**Comment by spjeff** [comment]
When you type "$host.version" what do you see?    This script requires PowerShell 3.0 at a minimum.   You probably need to upgrade from PS2 to PS3.   The most current version of PowerShell is now 5.0.

http://powershell.org/get-ciminstance-from-powershell-2-0/

**Comment by pwilliams134** [comment]
PS2 will upgrade. Thank you
